version: "1.0"
info:
  model: int-scaffold
packages:
- name: SobeysLoyaltyPointsPApi
  version: "1.0"
  gitServerName: githubTNK
  gitUrl: https://github.com/tnk1422
  gitUsername: tnk1422
  gitBranch: master
- name: SobeysPosEApi
  version: "1.0"
  gitServerName: githubTNK
  gitUrl: https://github.com/tnk1422
  gitUsername: tnk1422
  gitBranch: master
- name: SPOCProject
  gitServerName: githubTNKShared
  gitUrl: https://github.com/tnk1422
  gitUsername: tnk1422
  gitBranch: main
services:
- serviceName: project.spoc.integrations:common_getRefNumber
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: pub.string:indexOf
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
- serviceName: pub.string:substring
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
- serviceName: project.spoc.integrations:errorHandler
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: pub.json:documentToJSONString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
- serviceName: project.spoc.integrations:inquire
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: project.spoc.integrations:logContent
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: project.spoc.integrations:lps_accounts_s_api_inquire
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
- serviceName: project.spoc.integrations:map_member_inquire_response
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: pub.globalVariable:getGlobalVariable
  packages:
  - name: WmPublic
    version: 11.1.0.0.2097
- serviceName: project.spoc.integrations:redeem
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: project.spoc.integrations:redeem_lps_account_s_api
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: project.spoc.integrations:redeem_validate_pos_redeem_request
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: project.spoc.integrations:refund
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: project.spoc.integrations:refund_lps_account_s_api
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: project.spoc.integrations:refund_validate_pos_refund_request
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: project.spoc.integrations:validate_pos_inquire_request
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
- serviceName: project.spoc.integrations:wf_redeem_pos_e_api
  packages:
  - name: SPOCProject
    version: "1.0"
  - name: SobeysPosEApi
    version: "1.0"
  - name: SobeysLoyaltyPointsPApi
    version: "1.0"
