version: "1.0"
info:
  model: int-scaffold
packages:
- name: SPOCProject
  gitServerName: githubTNK
  gitUrl: https://github.com/tnk1422
  gitUsername: tnk1422
  gitBranch: main
- name: SobeysPosEApi
  gitServerName: githubTNK
  gitUrl: https://github.com/tnk1422
  gitUsername: tnk1422
  gitBranch: master
- name: SobeysLoyaltyAccountsPApi
  gitServerName: githubTNK
  gitUrl: https://github.com/tnk1422
  gitUsername: tnk1422
  gitBranch: master
- name: SobeysLoyaltyPointsPApi
  gitServerName: githubTNK
  gitUrl: https://github.com/tnk1422
  gitUsername: tnk1422
  gitBranch: master
- name: SobeysLpsAccountSApi
  gitServerName: githubTNK
  gitUrl: https://github.com/tnk1422
  gitUsername: tnk1422
  gitBranch: master
